-- ============================================================
-- Migration: Public Schema — Business Tables
-- PostgreSQL 18
-- Run order: 03_public.sql
-- Depends on: 01_schemas.sql, 02_reference.sql
-- ============================================================
-- UUID strategy: uuidv7() is a native function in PostgreSQL 18
-- (pg_catalog.uuidv7). It generates time-ordered UUIDs (v7),
-- improving B-tree index locality compared to random UUIDv4.
-- The DEFAULT on each surrogate id column ensures the database
-- generates the value when the application omits it.
-- NOTE: uuidv7() is used only on surrogate PKs that the DB
-- generates. Extension table PKs that are FK references (e.g.
-- nodeLockedLicenseData.licenseId) carry no DEFAULT because their
-- value must equal the parent row's id.
--
-- Index strategy: non-unique indexes are intentionally deferred
-- pending real query profile data. Exceptions: heartbeats indexes
-- (time-series BRIN + sessionId btree) are included from day one
-- as the partitioning strategy requires them.
-- ============================================================

-- ------------------------------------------------------------
-- public."vendors"
-- ------------------------------------------------------------

CREATE TABLE "vendors" (
    "id"           UUID        PRIMARY KEY DEFAULT uuidv7(),
    "email"        TEXT        NOT NULL UNIQUE,
    "passwordHash" TEXT        NOT NULL,
    "createdAt"    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt"    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "deletedAt"    TIMESTAMPTZ
);

COMMENT ON TABLE  "vendors"                IS 'Software vendors who use the platform to issue, track, and enforce licenses for their products. Root multi-tenant boundary: all RLS policies are anchored to vendors.id.';
COMMENT ON COLUMN "vendors"."id"           IS 'Surrogate primary key generated by uuidv7(). Time-ordered for B-tree locality. Used as the tenant identifier in all RLS policies.';
COMMENT ON COLUMN "vendors"."email"        IS 'Vendor login email address; globally unique across all vendors.';
COMMENT ON COLUMN "vendors"."passwordHash" IS 'bcrypt hash of the vendor password (minimum 12 rounds). The raw password is never persisted.';
COMMENT ON COLUMN "vendors"."createdAt"    IS 'Timestamp when the vendor account was first created.';
COMMENT ON COLUMN "vendors"."updatedAt"    IS 'Timestamp of the most recent update to any vendor field; must be set by the application on every write.';
COMMENT ON COLUMN "vendors"."deletedAt"    IS 'Soft-delete marker. Non-NULL means the vendor account is deactivated. All downstream data is retained for audit purposes.';

-- ------------------------------------------------------------
-- public."licenses"
-- ------------------------------------------------------------

CREATE TABLE "licenses" (
    "id"                UUID        PRIMARY KEY DEFAULT uuidv7(),
    "vendorId"          UUID        NOT NULL REFERENCES "vendors"("id")                     ON DELETE RESTRICT,
    "clientId"          UUID,
    "licenseStatusCode" TEXT        NOT NULL REFERENCES reference."licenseStatuses"("code") ON DELETE RESTRICT,
    "expiresAt"         TIMESTAMPTZ,
    "maxGraceSecs"      INTEGER     NOT NULL,
    "metadata"          JSONB,
    "createdAt"         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "deletedAt"         TIMESTAMPTZ,
    CONSTRAINT "licenses_maxGraceSecs_positive" CHECK ("maxGraceSecs" > 0)
);

COMMENT ON TABLE  "licenses"                     IS 'Licenses issued by vendors to customers. Root entity for activation, session management, and audit trail. License type is determined by the presence of a corresponding extension table row (e.g. nodeLockedLicenseData) — no type column is stored here.';
COMMENT ON COLUMN "licenses"."id"                IS 'Surrogate primary key generated by uuidv7().';
COMMENT ON COLUMN "licenses"."vendorId"          IS 'Owning vendor. Enforces multi-tenancy: identifies which vendor issued this license. RLS policies filter on this column.';
COMMENT ON COLUMN "licenses"."clientId"          IS 'Nullable forward-compatibility placeholder for the v1.0 clients table. Allows logical grouping of licenses by customer UUID without a FK constraint in MVP. No referential integrity enforced until the clients table exists.';
COMMENT ON COLUMN "licenses"."licenseStatusCode" IS 'Current stored lifecycle status of the license. FK to reference.licenseStatuses. EXPIRED is not a valid stored status; expiry is derived at query time from expiresAt.';
COMMENT ON COLUMN "licenses"."expiresAt"         IS 'Optional expiry timestamp. NULL means perpetual. Always evaluated at query time via (NOW() > expiresAt); never mutates licenseStatusCode automatically.';
COMMENT ON COLUMN "licenses"."maxGraceSecs"      IS 'Seconds permitted between consecutive successful heartbeats before a session is classified as a zombie. License-level policy shared by all sessions under this license. No column DEFAULT: the application must always supply an explicit value to prevent silent misconfiguration.';
COMMENT ON COLUMN "licenses"."metadata"          IS 'Arbitrary vendor-defined key-value metadata (e.g. product tier, feature flags). Nullable. The platform does not interpret or validate this field.';
COMMENT ON COLUMN "licenses"."createdAt"         IS 'Timestamp when the license was created.';
COMMENT ON COLUMN "licenses"."deletedAt"         IS 'Soft-delete marker. Non-NULL means the license has been removed from active use but is retained for audit history.';

-- ------------------------------------------------------------
-- public."nodeLockedLicenseData"
-- ------------------------------------------------------------

CREATE TABLE "nodeLockedLicenseData" (
    "licenseId"             UUID    PRIMARY KEY REFERENCES "licenses"("id") ON DELETE RESTRICT,
    "licenseKey"            TEXT    NOT NULL UNIQUE,
    "deviceFingerprintHash" TEXT,
    "maxSessions"           INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "nodeLocked_maxSessions_positive" CHECK ("maxSessions" > 0)
);

COMMENT ON TABLE  "nodeLockedLicenseData"                        IS 'Extension table for the node-locked license subtype. The presence of a row for a given licenseId indicates that license is node-locked. Future subtypes each receive their own extension table; no type discriminator column is required on licenses. Storing licenseKey here rather than on licenses keeps the activation mechanism specific to this subtype.';
COMMENT ON COLUMN "nodeLockedLicenseData"."licenseId"            IS 'FK to and PK of the parent license row. Enforces a strict 1:1 relationship. ON DELETE RESTRICT prevents the parent license from being deleted while this extension row exists.';
COMMENT ON COLUMN "nodeLockedLicenseData"."licenseKey"           IS 'Cryptographically random, human-legible activation key distributed to the end customer (e.g. XXXX-XXXX-XXXX-XXXX). Globally unique across all licenses.';
COMMENT ON COLUMN "nodeLockedLicenseData"."deviceFingerprintHash" IS 'SHA-256 hash of the combined device hardware identifiers (BIOS UUID + CPU serial + disk serial) computed server-side. Raw identifiers are never persisted. NULL until the first activation; set on first successful activation and verified on every subsequent heartbeat.';
COMMENT ON COLUMN "nodeLockedLicenseData"."maxSessions"          IS 'Maximum number of concurrent ACTIVE sessions permitted on this licensed device. Default 1. Prevents a single node-locked license from running as multiple parallel processes (e.g. in a container cluster).';

-- ------------------------------------------------------------
-- public."sessions"
-- ------------------------------------------------------------

CREATE TABLE "sessions" (
    "id"                    UUID        PRIMARY KEY DEFAULT uuidv7(),
    "licenseId"             UUID        NOT NULL REFERENCES "licenses"("id")                    ON DELETE RESTRICT,
    "sessionStatusCode"     TEXT        NOT NULL REFERENCES reference."sessionStatuses"("code") ON DELETE RESTRICT,
    "sessionToken"          TEXT        NOT NULL UNIQUE,
    "deviceFingerprintHash" TEXT        NOT NULL,
    "createdAt"             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "lastHeartbeatAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "metadata"              JSONB
);

COMMENT ON TABLE  "sessions"                      IS 'Active and historical sessions created via license activation. Hot-read table for heartbeat validation. On a successful CONTINUE heartbeat, only lastHeartbeatAt is updated in-place; no row is appended. Non-CONTINUE events (errors, revocations, expirations) are appended to the heartbeats table.';
COMMENT ON COLUMN "sessions"."id"                IS 'Surrogate primary key generated by uuidv7().';
COMMENT ON COLUMN "sessions"."licenseId"         IS 'License this session was activated against. Joined on every heartbeat to retrieve maxGraceSecs, licenseStatusCode, and expiresAt.';
COMMENT ON COLUMN "sessions"."sessionStatusCode" IS 'Stored lifecycle state of the session (ACTIVE, REVOKED, ZOMBIE, CLEANUP). Derived states (grace period exceeded, license expired) are computed at query time.';
COMMENT ON COLUMN "sessions"."sessionToken"      IS 'Cryptographically random opaque token issued to the SDK on activation. Used to identify the session on all subsequent heartbeat requests. Must be treated as a secret: it is the sole bearer credential for heartbeat calls.';
COMMENT ON COLUMN "sessions"."deviceFingerprintHash" IS 'Snapshot of the device fingerprint hash captured at session creation. Intentionally denormalized from nodeLockedLicenseData to eliminate a JOIN on the hot-path heartbeat validation query.';
COMMENT ON COLUMN "sessions"."createdAt"         IS 'Timestamp when the session was created, equivalent to the first activation timestamp for this device+license pair.';
COMMENT ON COLUMN "sessions"."lastHeartbeatAt"   IS 'Timestamp of the most recent successful (CONTINUE) heartbeat. Updated in-place on every successful heartbeat. Grace-period check: (NOW() - lastHeartbeatAt) > licenses.maxGraceSecs.';
COMMENT ON COLUMN "sessions"."metadata"          IS 'Arbitrary session metadata captured at activation time (e.g. SDK version, OS, hostname). Nullable. Not mutated after session creation.';

-- ------------------------------------------------------------
-- public."heartbeats"
-- ------------------------------------------------------------
-- Append-only time-series log for non-CONTINUE heartbeat events.
-- Successful CONTINUE heartbeats update sessions.lastHeartbeatAt
-- only and are NOT appended here to keep write amplification low.
-- Composite PK (id, heartbeatAt) is required by PostgreSQL: all
-- partition key columns must be included in the primary key of a
-- declaratively partitioned table.
-- ------------------------------------------------------------

CREATE TABLE "heartbeats" (
    "id"                      UUID        NOT NULL DEFAULT uuidv7(),
    "sessionId"               UUID        NOT NULL REFERENCES "sessions"("id")                           ON DELETE CASCADE,
    "heartbeatRespStatusCode" TEXT        NOT NULL REFERENCES reference."heartbeatRespStatuses"("code") ON DELETE RESTRICT,
    "errorCode"               TEXT        REFERENCES reference."errorCodes"("code")                     ON DELETE RESTRICT,
    "heartbeatAt"             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id", "heartbeatAt")
) PARTITION BY RANGE ("heartbeatAt");

COMMENT ON TABLE  "heartbeats"                            IS 'Append-only time-series log of non-CONTINUE heartbeat events (errors, revocations, expirations, refresh triggers). CONTINUE heartbeats are not appended here; they only update sessions.lastHeartbeatAt. Range-partitioned by heartbeatAt for efficient time-range archival and partition pruning.';
COMMENT ON COLUMN "heartbeats"."id"                      IS 'Unique identifier for the heartbeat record, generated by uuidv7(). Forms a composite PK with heartbeatAt: PostgreSQL requires all partition key columns to be included in the primary key of a partitioned table.';
COMMENT ON COLUMN "heartbeats"."sessionId"               IS 'Session that emitted this heartbeat event. ON DELETE CASCADE removes all heartbeat rows when the parent session is hard-deleted during retention cleanup.';
COMMENT ON COLUMN "heartbeats"."heartbeatRespStatusCode" IS 'Response code returned to the SDK for this heartbeat event. Only non-CONTINUE responses are recorded here.';
COMMENT ON COLUMN "heartbeats"."errorCode"               IS 'Error code if the heartbeat resulted in an ERROR response. NULL for non-error anomaly events (REFRESH, REVOKED, EXPIRED).';
COMMENT ON COLUMN "heartbeats"."heartbeatAt"             IS 'Timestamp when the heartbeat event was received. Partition key for range-based archival. BRIN index supports efficient time-range scans with minimal write overhead.';

-- Partitions: pre-create 5 quarters covering 2026 and 2027 Q1.
-- Add future partitions before the current quarter boundary.

CREATE TABLE "heartbeats_2026_q1" PARTITION OF "heartbeats" FOR VALUES FROM ('2026-01-01') TO ('2026-04-01');
CREATE TABLE "heartbeats_2026_q2" PARTITION OF "heartbeats" FOR VALUES FROM ('2026-04-01') TO ('2026-07-01');
CREATE TABLE "heartbeats_2026_q3" PARTITION OF "heartbeats" FOR VALUES FROM ('2026-07-01') TO ('2026-10-01');
CREATE TABLE "heartbeats_2026_q4" PARTITION OF "heartbeats" FOR VALUES FROM ('2026-10-01') TO ('2027-01-01');
CREATE TABLE "heartbeats_2027_q1" PARTITION OF "heartbeats" FOR VALUES FROM ('2027-01-01') TO ('2027-04-01');

-- Heartbeat indexes are exceptions to the deferred index policy:
-- the time-series partitioning strategy requires the BRIN index
-- from day one, and sessionId is the primary FK access pattern.

CREATE INDEX "heartbeats_sessionId_idx"   ON "heartbeats" ("sessionId");
CREATE INDEX "heartbeats_heartbeatAt_idx" ON "heartbeats" USING BRIN ("heartbeatAt");

-- ------------------------------------------------------------
-- public."licenseVersions"
-- ------------------------------------------------------------

CREATE TABLE "licenseVersions" (
    "id"            UUID        PRIMARY KEY DEFAULT uuidv7(),
    "licenseId"     UUID        NOT NULL REFERENCES "licenses"("id") ON DELETE RESTRICT,
    "vendorId"      UUID        NOT NULL REFERENCES "vendors"("id")  ON DELETE RESTRICT,
    "changeType"    TEXT        NOT NULL,
    "previousState" JSONB       NOT NULL,
    "newState"      JSONB       NOT NULL,
    "changedBy"     TEXT        NOT NULL,
    "changeReason"  TEXT,
    "changedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  "licenseVersions"               IS 'Immutable append-only log of all license state changes. Distinct from audit.auditLogs: this table tracks the evolution of the license business object for point-in-time reconstruction; auditLogs tracks who performed an action and from which IP. Both records are written transactionally on any mutating license operation.';
COMMENT ON COLUMN "licenseVersions"."id"          IS 'Surrogate primary key generated by uuidv7().';
COMMENT ON COLUMN "licenseVersions"."licenseId"   IS 'License whose state was changed.';
COMMENT ON COLUMN "licenseVersions"."vendorId"    IS 'Denormalized vendor ID for efficient RLS filtering and vendor-scoped historical queries without a JOIN through licenses.';
COMMENT ON COLUMN "licenseVersions"."changeType"  IS 'Categorical label describing the nature of the change (e.g. LICENSE_CREATED, LICENSE_EXTENDED, DEVICE_UPDATED, LICENSE_REVOKED, LICENSE_REACTIVATED).';
COMMENT ON COLUMN "licenseVersions"."previousState" IS 'Full JSONB snapshot of the license row immediately before this change. Enables complete rollback diffing and point-in-time reconstruction.';
COMMENT ON COLUMN "licenseVersions"."newState"    IS 'Full JSONB snapshot of the license row immediately after this change.';
COMMENT ON COLUMN "licenseVersions"."changedBy"   IS 'Identifier of the actor who made the change: vendor UUID for manual changes, or the string "system" for automated transitions (e.g. expiry jobs).';
COMMENT ON COLUMN "licenseVersions"."changeReason" IS 'Optional human-readable justification for the change (e.g. "Device stolen, reactivation requested by customer"). Useful for customer support and dispute resolution.';
COMMENT ON COLUMN "licenseVersions"."changedAt"   IS 'Timestamp when this version entry was recorded. Immutable after insertion.';

CREATE INDEX "licenseVersions_licenseId_idx"          ON "licenseVersions" ("licenseId");
CREATE INDEX "licenseVersions_vendorId_changedAt_idx"  ON "licenseVersions" ("vendorId", "changedAt" DESC);
