-- ============================================================
-- Migration: Audit Schema — Immutable Audit Tables
-- PostgreSQL 18
-- Run order: 04_audit.sql (last)
-- Depends on: 01_schemas.sql, 02_reference.sql, 03_public.sql
-- ============================================================
-- All tables in this file belong to the audit schema.
-- Separating audit tables into their own schema:
--   1) Enables a dedicated DB role with INSERT-only access on
--      audit.* and no UPDATE/DELETE, enforcing append-only
--      semantics at the database permission layer.
--   2) Reduces row lock contention between the high-throughput
--      public business tables and the audit write path.
--   3) Enables schema-level GRANT/REVOKE without touching
--      public schema objects (least-privilege by default).
--
-- Design pattern: core audit.auditLogs row captures what action
-- was taken, from which IP, via which user agent, and when.
-- Junction tables (auditLogVendorActors, auditLogLicenses,
-- auditLogSessions) record WHO performed the action and WHICH
-- resource was affected. Separating actor and resource into
-- junction tables allows new actor types (e.g. auditLogClientActors)
-- and new resource types to be added as new tables without any
-- migration of existing audit rows.
--
-- Cross-schema FK references use fully qualified names:
--   reference."actions", public."vendors", public."licenses",
--   public."sessions", audit."auditLogs"
-- ============================================================

-- ------------------------------------------------------------
-- audit."auditLogs"
-- ------------------------------------------------------------

CREATE TABLE audit."auditLogs" (
    "id"         UUID        PRIMARY KEY DEFAULT uuidv7(),
    "actionCode" TEXT        NOT NULL REFERENCES reference."actions"("code") ON DELETE RESTRICT,
    "ipAddress"  INET,
    "userAgent"  TEXT,
    "createdAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  audit."auditLogs"             IS 'Core audit log table. Immutable append-only record of every auditable system event. Captures the security and compliance context: what action was performed, from which IP, via which user agent, and when. The actor (who) and the affected resource (what subject) are captured in separate per-type junction tables, allowing new actor and resource types to be added without migrating this table.';
COMMENT ON COLUMN audit."auditLogs"."id"        IS 'Surrogate primary key generated by uuidv7(). Time-ordered for chronological B-tree locality. Referenced as a FK in all audit junction tables.';
COMMENT ON COLUMN audit."auditLogs"."actionCode" IS 'Resource-agnostic action verb performed. FK to reference.actions. The resource type and ID are captured in the corresponding junction table (auditLogLicenses, auditLogSessions, etc.).';
COMMENT ON COLUMN audit."auditLogs"."ipAddress" IS 'Client IP address at time of the action. Stored as INET type to support efficient IP range queries and subnet filtering for anomaly detection.';
COMMENT ON COLUMN audit."auditLogs"."userAgent" IS 'HTTP User-Agent header from the request. Used to identify SDK versions, detect automated scripts, and flag anomalous client behaviour during security investigations.';
COMMENT ON COLUMN audit."auditLogs"."createdAt" IS 'Timestamp when this audit entry was recorded. Always UTC. Immutable after insertion.';

-- ------------------------------------------------------------
-- audit."auditLogVendorActors"
-- ------------------------------------------------------------

CREATE TABLE audit."auditLogVendorActors" (
    "auditLogId" UUID NOT NULL PRIMARY KEY REFERENCES audit."auditLogs"("id")  ON DELETE CASCADE,
    "vendorId"   UUID NOT NULL             REFERENCES public."vendors"("id")   ON DELETE RESTRICT
);

COMMENT ON TABLE  audit."auditLogVendorActors"              IS 'Junction table associating an audit log entry with the vendor who performed the action. At most one vendor actor per audit entry (PK enforces this). In v1.0, auditLogClientActors will be added as a separate table using the same pattern — no migration of existing audit rows needed.';
COMMENT ON COLUMN audit."auditLogVendorActors"."auditLogId" IS 'FK to the core audit log entry. Also the PK of this table, enforcing at most one vendor actor per audit entry.';
COMMENT ON COLUMN audit."auditLogVendorActors"."vendorId"   IS 'Vendor who performed the audited action. ON DELETE RESTRICT prevents deletion of a vendor while audit trail entries remain.';

CREATE INDEX "auditLogVendorActors_vendorId_idx" ON audit."auditLogVendorActors" ("vendorId");

-- ------------------------------------------------------------
-- audit."auditLogLicenses"
-- ------------------------------------------------------------

CREATE TABLE audit."auditLogLicenses" (
    "auditLogId" UUID  NOT NULL PRIMARY KEY REFERENCES audit."auditLogs"("id")  ON DELETE CASCADE,
    "licenseId"  UUID  NOT NULL             REFERENCES public."licenses"("id")  ON DELETE RESTRICT,
    "changes"    JSONB
);

COMMENT ON TABLE  audit."auditLogLicenses"              IS 'Junction table identifying a license as the resource affected by an audited action. Stores license-specific mutation context in the optional changes column.';
COMMENT ON COLUMN audit."auditLogLicenses"."auditLogId" IS 'FK to the core audit log entry. Also the PK of this table, enforcing at most one license resource per audit entry.';
COMMENT ON COLUMN audit."auditLogLicenses"."licenseId"  IS 'The license that was the subject of the audited action. ON DELETE RESTRICT prevents deletion of a license while audit trail entries remain.';
COMMENT ON COLUMN audit."auditLogLicenses"."changes"    IS 'Nullable JSONB diff capturing license-specific mutation context (e.g. {"licenseStatusCode": {"from": "ACTIVE", "to": "REVOKED"}}). NULL for read or query actions where no mutation occurred.';

-- ------------------------------------------------------------
-- audit."auditLogSessions"
-- ------------------------------------------------------------

CREATE TABLE audit."auditLogSessions" (
    "auditLogId" UUID  NOT NULL PRIMARY KEY REFERENCES audit."auditLogs"("id")  ON DELETE CASCADE,
    "sessionId"  UUID  NOT NULL             REFERENCES public."sessions"("id")  ON DELETE RESTRICT,
    "changes"    JSONB
);

COMMENT ON TABLE  audit."auditLogSessions"              IS 'Junction table identifying a session as the resource affected by an audited action. Stores session-specific mutation context in the optional changes column.';
COMMENT ON COLUMN audit."auditLogSessions"."auditLogId" IS 'FK to the core audit log entry. Also the PK of this table, enforcing at most one session resource per audit entry.';
COMMENT ON COLUMN audit."auditLogSessions"."sessionId"  IS 'The session that was the subject of the audited action. ON DELETE RESTRICT prevents deletion of a session while audit trail entries remain.';
COMMENT ON COLUMN audit."auditLogSessions"."changes"    IS 'Nullable JSONB diff capturing session-specific mutation context (e.g. {"sessionStatusCode": {"from": "ACTIVE", "to": "REVOKED"}}). NULL for read or query actions where no mutation occurred.';
