name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}/${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch-python-versions:
    runs-on: ubuntu-latest
    outputs:
      supported_versions: ${{ steps.fetch-versions.outputs.supported_versions }}
      bound_versions: ${{ steps.fetch-versions.outputs.bound_versions }}
    steps:
      - name: Fetch Supported Python
        id: fetch-versions
        run: |
          versions=$(curl -fsSL https://endoflife.date/api/v1/products/python/ \
                     | jq '[ .result.releases[] | select(.isEol == false) | .label ]')

          echo "supported_versions=$(echo $versions | jq -c '.')"        >> $GITHUB_OUTPUT
          echo "bound_versions=$(echo $versions | jq -c '[.[0],.[-1]]')" >> $GITHUB_OUTPUT

  test_backend:
    needs: fetch-python-versions
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        python-version: ${{ fromJson(needs.fetch-python-versions.outputs.supported_versions) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --group dev

      - name: Unit tests
        working-directory: backend
        run: uv run coverage run -m pytest -svm unit

      - name: Integration tests
        working-directory: backend
        run: uv run coverage run --append -m pytest -svm integration

      - name: Generate coverage report
        working-directory: backend
        run: uv run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          use_oidc: true
          verbose: true

  test_migrations:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7

      - name: Migration tests
        run: |
          uv run --with coverage,pytest-cov \
            python -m pytest migrations/test_migrations.py -n auto --cov --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          use_oidc: true
          verbose: true
